name = "my-ads-dashboard-app"
main = "src/index.js" # This might vary based on your Pages setup

# Define the Pages project type if not already there
# type = "javascript.react" # Or whatever your framework preset is

# Pages Functions specific configuration (usually automatic if 'functions' folder exists)
# The `functions` directory is automatically detected by Cloudflare Pages.

# D1 Database Bindings
[[d1_databases]]
binding = "DB" # This is the binding name used in your Pages Function (env.DB)
database_name = "aduserdb" # The name of your D1 database
database_id = "YOUR_D1_DATABASE_ID" # The ID of your D1 database from Cloudflare dashboard